val places = listOf(
    "Paris",
    "London",
    "New York",
    "Tokyo",
    "Berlin",
    "Sydney",
    "Amsterdam",
    "Barcelona",
    "Rome",
    "Venice",
    "Vienna",
    "Toronto",
    "Los Angeles",
    "San Francisco",
    "Madrid",
    "Seoul",
    "Dubai",
    "Moscow",
    "Hong Kong",
    "Singapore",
    "Bangkok",
    "Istanbul",
    "Athens",
    "Cape Town",
    "Rio de Janeiro",
    "Buenos Aires",
    "São Paulo",
    "Mexico City",
    "Vancouver",
    "Montreal",
    "Chicago",
    "Miami",
    "Las Vegas",
    "San Diego",
    "Boston",
    "Washington, D.C.",
    "Seattle",
    "New Orleans",
    "Nashville",
    "Austin",
    "Denver",
    "Phoenix",
    "Portland",
    "San Antonio",
    "Dallas",
    "Houston",
    "Atlanta",
    "Philadelphia",
    "Pittsburgh",
    "Detroit",
    "St. Louis",
    "Minneapolis",
    "Salt Lake City",
    "Albuquerque",
    "Kansas City",
    "Charlotte",
    "Indianapolis",
    "Cincinnati",
    "Cleveland",
    "Orlando",
    "Tampa",
    "Jacksonville",
    "Honolulu",
    "San Juan",
    "Havana",
    "Dublin",
    "Edinburgh",
    "Glasgow",
    "Manchester",
    "Birmingham",
    "Liverpool",
    "Belfast",
    "Stockholm",
    "Oslo",
    "Copenhagen",
    "Helsinki",
    "Reykjavik",
    "Dubrovnik",
    "Santorini",
    "Mykonos",
    "Crete",
    "Ibiza",
    "Mallorca",
    "Tenerife",
    "Gran Canaria",
    "Lanzarote",
    "Phuket",
    "Bali",
    "Krabi",
    "Koh Samui",
    "Hoi An",
    "Luang Prabang",
    "Siem Reap",
    "Yangon",
    "Hanoi",
    "Ho Chi Minh City",
    "Melbourne",
    "Brisbane",
    "Adelaide",
    "Perth",
    "Auckland",
    "Wellington",
    "Christchurch",
    "Queenstown",
    "Fiji",
    "Tahiti"
)
